### ISSUE TITLE
Haddocks for lookupSOA need an update?

### ISSUE THREAD

**Issue by qrilka** [kazu-yamamoto/dns#106]
At https://hackage.haskell.org/package/dns-3.0.2/docs/Network-DNS-Lookup.html#v:lookupSOA I see description talking about "minimum TTL" but as of https://tools.ietf.org/html/rfc2308 (issued 20 years ago) last value of SOA record should be used for negative caching, not as a mimimum TTL, see e.g. https://serverfault.com/a/658371/89369

**Comment by kazu-yamamoto** [comment]
Relating to: https://github.com/kazu-yamamoto/dns/commit/c17cc8d736524c214ddfe8f1fc32dad5bb2e218d

**Comment by kazu-yamamoto** [comment]
@qrilka I think you are right.

@vdukhovni You know better than me in this area. What do you think?

**Comment by vdukhovni** [comment]
The field is still called the "minimum" field, and is a TTL value. Anyone intending to use it will know what it is. The documentation is not providing definitions of the fields, just listing their names, so I think it is fine. Caching resolvers cache negative answers based on the TTL of the SOA record in the authority section, which an authoritative server populates with an SOA record whose TTL is set to the minimum value from the SOA record, and iterative resolvers set from the remaining negative TTL of the requested record.

If a description beyond:
```
domain, mailbox, serial number, refresh time, retry time, expiration time, and minimum TTL
```
were provided, then one might explain the current purpose of the field.

That said, the text says "domain" instead of "mname" (reported name of the master nameserver for the zone), and "mailbox" instead of "rname"...

It might be more clear to list the verbatim RFC1035 names:  `mname, rname, serial, refresh, retry, expire, minimum` noting only that the "." between the first label and second labels of the "rname" mailbox is replaced by "@" and the trailing "." is for now retained (but might be removed in the future)

**Comment by vdukhovni** [comment]
Some of the explanation of rname (but not the presentation syntax, with `@` after the first label) is explained at:

https://hackage.haskell.org/package/dns-3.0.2/docs/Network-DNS-Types.html#t:Mailbox

**Comment by qrilka** [comment]
@vdukhovni using `minimum` without TTL in it looks fine to me, my complaint was mainly about phrase "This can be useful to validate TTLs for a server" which IMO is not quite correct. And these words look like a "description beyond" to me.

**Comment by vdukhovni** [comment]
I would remove the sentence:
```
This can be useful to validate TTLs for a server or get an abuse contact address for a domain.
```
people who want the SOA record will know what it contains from other sources. We're just describing how the data is returned. So the list and types of fields, plus encoding details of the rname are largely sufficient.

While describing syntax (not semantics) we might also mention that the "rname" round-trips.  That is, the "@" sign is both produced when decoding from wire form, and consumed when encoding to wire form, thereby allowing for first labels with internal "."s.

**Comment by kazu-yamamoto** [comment]
@vdukhovni It would be appreciated if you kindly send a PR for this.

**Comment by kazu-yamamoto** [comment]
Ping @vdukhovni

**Comment by kazu-yamamoto** [comment]
Closing this thanks to #108.
