### ISSUE TITLE
Supporting SVCB and HTTPS RR

### ISSUE THREAD

**Issue by kazu-yamamoto** [kazu-yamamoto/dns#169]
- HTTPS RR https://datatracker.ietf.org/doc/html/draft-ietf-dnsop-svcb-https-10
- Unknown RR https://datatracker.ietf.org/doc/html/rfc3597

**Comment by kazu-yamamoto** [comment]
@vdukhovni Do you have any ideas on how to represent a list of key/value pairs in `RData`? Is `[(key,value)]` (where `key` and `value` are proper types) good enough?

**Comment by vdukhovni** [comment]
> @vdukhovni Do you have any ideas on how to represent a list of key/value pairs in `RData`? Is `[(key,value)]` (where `key` and `value` are proper types) good enough?

Well, that rather depends on what you have in mind when you say "proper types", but I rather think that capturing this data type requires a bit more sophistication:

* What we have is an ordered list of Word16 keys with an associated value whose type depends on the key!

Ignoring ordering for the moment, I'm thinking of a bunch of key types with associated types for their payloads:

```haskell

class (Typeable a) => SvcParam a where
     svcKeyNum   :: proxy a -> Word16             -- 16 bit wire key
     svcKeyName :: proxy a -> ByteString        -- lower-case LDH presentation key name
     svcValueEncode :: a -> ByteString             -- Serialize to wire form
     svcValueDecode :: ByteString -> a            -- Decode from wire form
     svcValueParse :: ByteString -> a               -- Decode from presentation form
     svcValueUnparse :: a -> ByteString          -- Encode to presentation form

     fromSvcParam :: SomeSvcParam -> Maybe a
     fromSvcParam (SomeSvcParam p) = cast p

     toSvcParam :: a -> SomeSvcParam
     toSvcParam = SomeSvcParam

-- Existential wrapper 
data SomeSvcParam = forall a. SvcParam a => SomeSvcParam a

data MandatoryKeys = M [Word16]
instance SvcParam MandatoryKeys where
     svcKeyNum _ = 0
     svcKeyName _ = "mandatory"
     ...

...
```
Suitably fleshed out with types and instances for the registered key slots as well as as a bunch of type-level nat indexed types (constrained to lie in [0..0xffff]) for unknown keys, with the generic wire codecs being the identity function, and presentation just doing ByteString escaping/unescaping.

Then a built-in mechanism to map known key names to key values, lookup functions, ... this will take a bit of design effort, but I do think that the payloads for each known key index need to be correctly typed.  I think we can avoid the singleton library, because the key types only appear as phantom arguments.

This means that the encode and decode methods will need to have access to a lookup table that maps Word16 key indices to `ByteString -> Either DNSError SomeServiceParam`, and that it should be possible to augment this map in the resolver configuration. The decoder can check the list of key indices is strictly monotone...

**Comment by kazu-yamamoto** [comment]
If we use this kind of typeclass, it's easy to add a new instance of `SvcParam`.
It's nice.

The dilemma is `RData` which uses a sum type resulting in giving up the extensibility.
Should we also modify `RData` using a typeclass or keep it as is?

**Comment by vdukhovni** [comment]
The existential wrapper hides the polymorphism.  The RData can be just `[SomeSrcParam]`.

**Comment by kazu-yamamoto** [comment]
I'm not talking about `RD_SVCB [SomeSrcParam]` but talking about the entire `RData`. Currently `RData` is not extensible. If we introduce a typeclass like `SvcParam`, I guess it gets extensible. I'm wondering whether or not it's worth doing.

**Comment by vdukhovni** [comment]
I see, yes, ultimately in some new DNS library `RData` would also be handled existentially, and be extensible.  I actually have a prototype of just the basic classes and codecs (without any of the IO layers, ...), but have put it aside for lack of time.

I don't think this is easy to retrofit into the current design, it would be a completely new library I think.

**Comment by kazu-yamamoto** [comment]
Thanks. I will pursue your approach only for SVCB and HTTPS this time.

**Comment by vdukhovni** [comment]
> Thanks. I will pursue your approach only for SVCB and HTTPS this time.

Probably best for now.  We can discuss where else extensibility through open type classes and existential quantification can be introduced without radically changing the API at some point later.  My instinct is that doing this to RDATA would be difficult to hide from the user, but perhaps I'm wrong.  My prototype made various additional ambitious departures, but it is far from a usable library, just some type definitions and some codecs. Perhaps something more modest could be more compatible, but I'm not sure.

**Comment by kazu-yamamoto** [comment]
I agree. Thank you as always.

**Comment by kazu-yamamoto** [comment]
@vdukhovni It is quite easy to use `svcValueEncode` since a value of `a` exists in advance.

However, I don't know how to use `svcValueDecode`. When parsing, we get an integer (which represents its type). How to call a proper `svcValueDecode`?

If this approach is not extensible, we can pass a static dictionary whose key is an integer and value is a function (`:: SomeSvcParam -> ByteString`). To make it extensible, should we disclose this dictionary to users?

Or are there any magic where a kind of reflection solves extensibility automatically?

**Comment by vdukhovni** [comment]
Yes, we need a table.  A built-in one for the known parameters, and a means for the user to add more known types in the resolver configuration. This would indeed be an IntMap to a proxy or a `Dict`:

```haskell
import Data.Constraint

type SvcParamMap = Map Int SvcParamDict
data SvcParamDict = forall a. (SvcParam a) => SvcParamDict (Dict a)
```
The dictionary should be sufficient to handle the decoding.

**Comment by vdukhovni** [comment]
Also when there is no entry in the map, we need to decode the parameter to a generic representation, with a type-level natural for its parameter number.
