### ISSUE TITLE
multiple servers support

### ISSUE THREAD

**Issue by l29ah** [kazu-yamamoto/dns#28]
dns-1.4.5 fails if the first `nameserver` entry in /etc/resolv.conf is offline, ignoring the others

**Comment by riaqn** [comment]
By far only the first `nameserver` entry  in `/etc/resolv.conf` is read.

**Comment by riaqn** [comment]
The library doesn't have to support multiple servers in its core because the expected behavier is quite ad-hoc(some people want to use the secondary server when the first fails, some people want the requests to be sent at the same time and use the first reply).

In the meantime we should make it easy for users to implement multiple servers. I think we can make a type class `Resolver`, and let our current resolver implementation an instance of it. Users thus can write "wrapper" resolver that actually pipes several  other resolvers, and make it another instance of it.

**Comment by kazu-yamamoto** [comment]
@riaqn Please go ahead and show me your code.

**Comment by riaqn** [comment]
I have just written a new DNS library here: http://github.com/riaqn/resolve

Basically it's what I mentioned above. Although `resolv.conf` is not supported yet, it would be very easy to implement due to the structure of the project(it would be simply another `Resolver`). I will add this feature when I have time.

By far, the library supports:
UDP query
TCP query
ID matching

TODO:
EDNS support
resolv.conf support.
