### ISSUE TITLE
TimeoutExpired returned immediately even with long timeout set

### ISSUE THREAD

**Issue by shmish111** [kazu-yamamoto/dns#50]
```haskell
let rc = DNS.defaultResolvConf { DNS.resolvInfo = consul, DNS.resolvTimeout = 10000000000000 }
rs <- DNS.makeResolvSeed rc
DNS.withResolver rs $ \resolver -> DNSL.lookupA resolver "riemann.service.dc1.consul."
=> Left TimeoutExpired
```

The last line returns immediately, it does not take 10000000000000  micro seconds as I would expect. The same thing happens with the default timeout value, I would expect it to take 3 seconds before returning with TimeoutExpired however it is immediate.

**Comment by adinapoli-iohk** [comment]
I think I know what's going on with this one. The problem is that there are two places where `TimeoutExpired` is used, and one is (imho) not appropriate:

https://github.com/kazu-yamamoto/dns/blob/master/Network/DNS/Resolver.hs#L364

Here we should throw something like `RetryLimitExceeded` or something like that. I can see if I can cook a PR and if I can make @kazu-yamamoto approve my work 😀
