### ISSUE TITLE
Constructors as pattern synonym (for GHC 8)

### ISSUE THREAD

**Issue by kazu-yamamoto** [kazu-yamamoto/dns#74]
The ordering of `RData` is different from https://www.iana.org/assignments/dns-parameters/dns-parameters.xhtml#dns-parameters-4

@vdukhovni Is it OK to reorder `RData` and `TYPE` according the IANA DB?

Relating to #41.

**Comment by vdukhovni** [comment]
Yes, I would not expect anyone to be relying on the ordering of of the TYPE enum and so ordering by the underlying IANA ordinals makes sense.  For DNSSEC only order within an RRset (same type) needs to be normalized for signing, order across RRsets is not material.  So it is likely not important to make such a change, it is mostly cosmetic.

As for RData, which non-standard properties of the current order did you have in mind?  Are the elements of some RData types out of order?

**Comment by kazu-yamamoto** [comment]
I would like to have the same ordering for `RData` as `TYPE`.
If we reorder `TYPE` according to the IANA DB, I would like to do the same reordering for `RData`.

**Comment by vdukhovni** [comment]
I see.  I  assume this just requires lexically ordering the RData sum type constructors in the source code by the numeric value of the underlying RRtype:

```
data RData = SIG0 ...         -- 0 (We'll probably start with RD_A until this is needed)
           | RD_A ...         -- 1
           | RD_NS ...        -- 2
           | RD_CNAME ...     -- 5
           | RD_SOA ...       -- 6
           ...
```

If that's what you mean, then sure, we can do that.  Are there any implications for `ABI` stability of inserting a new constructor in the middle of the list?  I am not aware of any "dynamic loading" or "dynamic linking" for facilities in Haskell, so perhaps the question of stable binary interfaces is moot?  Otherwise, one might argue that maintaining the current order when adding new constructors is more likely to produce a stable ABI...

**Comment by kazu-yamamoto** [comment]
> I see. I assume this just requires lexically ordering the RData sum type constructors in the source code by the numeric value of the underlying RRtype:

Yes!

>  Are there any implications for ABI stability of inserting a new constructor in the middle of the list? 

I'm not sure.

But we will do this change in a major release, so I think we don't have to worry too much.

**Comment by kazu-yamamoto** [comment]
The patch above on the `iana` branch is what I want to do.

**Comment by vdukhovni** [comment]
So it seems safe enough to re-order as you suggested, but I am not sure *why* we'd want to do that.  The numerical order of RRtypes is mere historical accident of the timing of the RFC that defines the RRtype.  The numbers are really just a *set* and the ability to compare them is AFAIK an irrelevant implementation detail.  That is, I don't know of any software or protocol that needs to order RRtypes, rather than just compare them for equality.

A more useful modernization might be to use pattern synonyms for the RRtype constants:

```
{-# LANGUAGE PatternSynonyms #-}
module Main (main)
    where

import Data.Word

newtype RRtype = RRtype { typeToInt :: Word16 }
   deriving (Eq)

pattern A = RRtype 1
pattern NS = RRtype 2

instance Show RRtype where
    show A = "A"
    show NS = "NS"
    show x = "TYPE" ++ (show $ typeToInt x)

main :: IO ()
main = do
    print A
    print NS
    print $ RRtype 4242
    print $ A == NS
    print $ NS == NS
```

**Comment by kazu-yamamoto** [comment]
> So it seems safe enough to re-order as you suggested, but I am not sure why we'd want to do that. 

I would like to reorder these data types for readability and maintainability. For instance, it gets easier to compare `TYPE` and `RData` line by line.

> The numerical order of RRtypes is mere historical accident of the timing of the RFC that defines the RRtype. The numbers are really just a set and the ability to compare them is AFAIK an irrelevant implementation detail. That is, I don't know of any software or protocol that needs to order RRtypes, rather than just compare them for equality.

If the ordering of `TYPE` is not important from this point of view, why should we continue this discussion? Let's just do it.

I will consider PatternSynonyms.

**Comment by vdukhovni** [comment]
Sounds like a plan.  Pattern synonyms will require GHC 8.0 or later to be useful, because the import syntax is otherwise too cumbersome.  With GHC 8.0 you can export patterns along with a type's constructors:

```
module FOO (TYPE(.., A, NS, ...)) where ...
```
at the cost of having to list each exported pattern explicitly, since AFAIK there's no sum type that collects all the patterns together.  The result is still I think more efficient and natural.  Curious what you think when you take a closer look.

**Comment by kazu-yamamoto** [comment]
I tried this idea. 

Advantage of this approach is that the code gets easier to maintain. Very nice.
Disadvantage is that we have to enumerate each patten to export.

Comparing advantage and disadvantage, I like this approach. I will implement this when we will support GHC 8.x or later only. So, let's keep this issue.

**Comment by kazu-yamamoto** [comment]
With CPP, I have implemented your idea. What do you think?

**Comment by vdukhovni** [comment]
Looks good for GHC 8, but might not work right for GHC <= 7, because the birectional pattern synonyms cannot be imported via the associated expression type.

Thus a client that says `import Network.DNS (TYPE(A, AAAA))` or `import Network.DNS (TYPE(..))` will not work, to get at `A` and `AAAA` it will to explicitly import the patterns separately from `TYPE`.

Perhaps I'm missing something, but it looks like an obstacle to me.  See `Bundling Pattern Synonyms` in https://mpickering.github.io/posts/2015-12-12-pattern-synonyms-8.html

**Comment by kazu-yamamoto** [comment]
I tested this lib GHC 7.10 and tests passed. So, I thought that this approach is also OK for GHC 7.x.
But yes, you are right. I missed the usage of `import Network.DNS (TYPE(..))`.
Let's keep this as future work.

**Comment by kazu-yamamoto** [comment]
Just for record. I found this bug (6675b3a31c52cc74ed60a2abbc915d7f7dcd6fd1) thanks to the reordering.

**Comment by vdukhovni** [comment]
Thanks for fixing the typo.  We'll revisit this issue in a couple of years or so, when it might be time to consider dropping support for GHC 7.x

**Comment by kazu-yamamoto** [comment]
Yes. I continue to maintain the `ghc8` (not `iana`) branch.

**Comment by kazu-yamamoto** [comment]
I have mixed the constructor approarch and the pattern synonym approach together in the `master` branch.
So, I close this issue and will remove the `ghc8` branch in the near future.

**Comment by vdukhovni** [comment]
Thanks, looks good.  For the record, I'd prefer if the branch were not deleted, but left in place with no further work...

**Comment by kazu-yamamoto** [comment]
OK. I will keep it.
