### ISSUE TITLE
Version 2.0.13

### ISSUE THREAD

**Issue by kazu-yamamoto** [kazu-yamamoto/dns#76]
Copying from #72:

> Hey! Just to be sure to be on the same page, can I summarise what you are saying? You are telling me that releasing the current `master` is a major release, so it shouldn't be rushed, but that we can still release `2.0.13` relative quickly if we drop the default DNS thing and we include only:
>
> * The `RetryLimitExceeded` patch;
> * The `sendAll` fix patch;
>
> Am I right?

@adinapoli-iohk I think that I have done all things above.
Please check https://github.com/kazu-yamamoto/dns/tree/version2.0.13

**Comment by adinapoli-iohk** [comment]
Hey @kazu-yamamoto ! It looks mostly ok, but didn't we decide to discard the "default Win DNS" from 2.0.13? I'm just asking as that C code we borrowed from `cardano` might need a bit of polishing to make it production-quality, as it's using `printf` for error reporting and on the Haskell side is returning a `Maybe` where it should really return an `Either` explaining the reason of the failure. I _think_ (but correct me if I'm wrong) it might be more prudent to drop the default Win DNS server from `2.0.13` but still keep the `RetryLimitExceeded` and `sendAll` patch. What do you think?

cc @rockbmb (the original creator of the C code) and @dcoutts for extra opinions 😉

**Comment by dcoutts** [comment]
I would indeed advise cleaning up the C code. We had intended to clean it up before submitting it, but @kazu-yamamoto beat us to it and included it! :-)

**Comment by kazu-yamamoto** [comment]
Ah. Sorry. I confused `RetryLimitExceeded` with  Win DNS.
I will revert Win DNS and include `RetryLimitExceeded` tomorrow.
(I need to leave our office now.)

**Comment by rockbmb** [comment]
If @kazu-yamamoto intends to implement something similar to `getWindowsDefaultDnsServer` in this package, then in order to avoid duplicating work I wouldn't mind making a PR here with the improved C code and then pointing the project we're working on (`cardano-sl`) to that commit until it's available on Hackage.

**Comment by kazu-yamamoto** [comment]
@rockbmb I have borrowed your code since nobody told me what I should do.
If possible, I would like to remove the code from `dns` and depend on your package.
Are you planning to release `sardano-sl` from HackageDB?

**Comment by rockbmb** [comment]
@kazu-yamamoto Hmm... Maybe @adinapoli-iohk can say otherwise, but I don't think that's a good idea. Since `cardano-sl` already depends on `dns`, adding `cardano-sl` as a dependency to `dns` would introduce a cyclical package dependency. I don't know if that would work.

Furthermore, `cardano-sl` is a very large project, and making `dns` depend on it would introduce hundreds of new dependencies that would vastly increase build times for `dns` and its reverse-dependencies.

**Comment by kazu-yamamoto** [comment]
OK. I understand the situation.
So, would you clean up the code of the Win DNS part in `dns` and send me a PR?

**Comment by kazu-yamamoto** [comment]
Note that I'm talking about the `master` branch.

**Comment by rockbmb** [comment]
Sounds good. I'll work with @adinapoli-iohk on it.

**Comment by kazu-yamamoto** [comment]
@adinapoli-iohk I did `push -f` for https://github.com/kazu-yamamoto/dns/tree/version2.0.13
If you are fine with this branch, I will release the new version.
Tests on AppVeyor fail because the default DNS server cannot be resolved.

**Comment by adinapoli-iohk** [comment]
Looks fantastic, @kazu-yamamoto , thank you very much! I'm very happy with releasing `2.0.13` in its current shape, as it fixes what I care about most (aka the `sendAll` shenanigans 😁 ).

I can work with @rockbmb on a separate feature branch to cleanup the default windows DNS server, for which I agree it should be committed and merged into `dns` so that downstream packages (like `cardano-sl`) can depend from just a single package with minimal dependencies.

Thank you for your time!

**Comment by kazu-yamamoto** [comment]
OK. A new version has been released.

**Comment by adinapoli-iohk** [comment]
Thank you very much!
