### ISSUE TITLE
StateBinary.getNByteString

### ISSUE THREAD

**Issue by kazu-yamamoto** [kazu-yamamoto/dns#91]
@themattchan I'm waiting for your PR to fix `getNByteString`.

**Comment by themattchan** [comment]
I've investigated this further, and I think what we really want to do it to get rid of `psPosition` completely and just use parsec's own position information, which does not get updated if the parse fails (in StateBinary we update regardless). Sadly `attoparsec` does not expose position info, so this would be very hard to correct without a lot of work. A way to do this would be to change `SGet` to be of type `SGet a = Parser ByteString (IntMap Domain, a)` and thread it through the parse result. 

Because `DNS` only uses the position in one place, `getDomain'`, which seems to work fine, I don't think that this is enough of an issue to fix. We should keep this problem in mind though, for when a problem with position checking arises.

**Comment by kazu-yamamoto** [comment]
> just use parsec's own position information

I don't understand this phrase. Are you proposing to use the `parsec` package?
Or is this a typo of "parser's"?

**Comment by themattchan** [comment]
Whoops, I meant `attoparsec`'s internal `pos` state, which is not exposed. How we're handling `psPosition` currently does not appear to be an issue though.

**Comment by kazu-yamamoto** [comment]
Yeah. `attoparsec` does not disclose the internal position. That's why I could not use `attoparsec`.

**Comment by vdukhovni** [comment]
We now also use `getPosition` when parsing `RRSIG`, `NSEC` and `NSEC3` records.  But what exactly is the problem this issue is about?  Is it still relevant?

**Comment by vdukhovni** [comment]
I think this issue can be closed. There does not seem to be anything actionable here...

**Comment by kazu-yamamoto** [comment]
Let's close.
